<a href="https://colab.research.google.com/github/ThePrax12/MLcourse/blob/main/NumPy/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy


[NumPy](https://numpy.org/) (Numerical Python) - это основная библиотека для выполнения вычислений с использованием многомерных массивов и матриц в Python. Она предоставляет обширный набор функций и операций для работы с массивами, что делает ее незаменимой для научных вычислений и анализа данных.

Основан NumPy на библиотеке LAPAC, которая написана на Fortran. Поэтому NumPy обеспечивает эффективные и быстрые операции над многомерными массивами, такие как сложение, умножение, транспонирование, вычисление статистических параметров и многое другое.

## Установка и подключение

Если вы используете Google Colab, то numpy уже установлен на виртуальном сервере и вы можете им пользоваться.

Если вы открыли собственный ноутбук, то можете воспользоваться командой установки, записанной через восклицательный знак


```
!comand
```
Так запущенная команда в среде ipy вызывает системную команду pip, которая сама установит данный модуль в вашу виртуальную среду.

Обратите внимание, что каждый ноутбк имеет свой набор используемых библиотек и системных установок.


In [ ]:
!pip install numpy

Для подключения модулей в Python используется команда `import` или её вариации. В случае с numpy есть традиционная и привычная всем команда импорта с использованием алиаса (as) np

Алиас - это встроенная команда интерпретатора для сокращения команд и их последовательностей.

In [ ]:
# классический вариант
import numpy

# numpy.func

In [ ]:
# традиционный вариант
import numpy as np

# np.func

Есть другой вариант, в котором можно использовать только команду без указания модуля. Но так как в разных модулях могут быть одинаковые функции, использовать такой вариант не рекомендуется.

In [ ]:
from numpy import *
from math import *
# sqrt(9)
# sqrt(9)

##Особые константы

In [ ]:
import numpy as np

# Математические константы
print("Число Пи:", np.pi)
print("Число e:", np.e)

# Специальные значения
print("Положительная бесконечность:", np.inf)
print("NaN (не число):", np.nan)


Число Пи: 3.141592653589793
Число e: 2.718281828459045
Положительная бесконечность: inf
NaN (не число): nan


##Массивы NumPy


Массивы в NumPy (numpy.array) представляют собой основную структуру данных в библиотеке NumPy. Они предоставляют мощные средства для хранения и манипуляций с многомерными данными.

Все элементы массива NumPy имеют одинаковый тип данных, что повышает производительность и упрощает вычисления.

Массивы NumPy реализованы на низкоуровневых языках программирования (C и Fortran), что обеспечивает высокую производительность и эффективность при выполнении операций над массивами

###Создание

Пример создания одномерного массива (из списка)

In [ ]:
a = np.array([1, 9, 3, 4], float)
print('Array:', a)
print('Тип: ',type(a))
# обратное преобразование
print(a.tolist())

Array: [1. 9. 3. 4.]
Тип:  <class 'numpy.ndarray'>
[1.0, 9.0, 3.0, 4.0]


Многомерные массивы более разнообразны и исползуются повсеместно.

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7,8,9]]

a = np.array(lst, int)

print(lst, end = '\n\n')
print(a, end = '\n\n')

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]



Копирование массивов

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7,8,9]]

a = np.array(lst, int)

b = a # неверно

a[0,0] = 123
print(b[0,0])

123


In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7,8,9]]

a = np.array(lst, int)

b = a.copy() # верно

a[0,0] = 123
print(b[0,0])

1


Специальные функции для создания массивов

In [ ]:
import numpy as np

# Создание массива нулей размером 2x3
zeros_array = np.zeros((2, 3))

# Создание массива единиц размером 3x2
ones_array = np.ones((3, 2))

# Создание массива последовательных чисел от 0 до 9 с шагом 2
range_array = np.arange(0, 10, 2)

# Создание единичной матрицы размером 3x3 (единицы на главной диагонали)
eye_matrix = np.eye(3)

# k - номер диагонали, заполненный единицами
eye_matrix_2 = np.eye(5,4, k=2)

eye_matrix_3 = np.eye(5,4, k=-2)

print(zeros_array,end = '\n\n')
print(ones_array,end = '\n\n')
print(range_array,end = '\n\n')
print(eye_matrix,end = '\n\n')
print(eye_matrix_2,end = '\n\n')
print(eye_matrix_3,end = '\n\n')


[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[0 2 4 6 8]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]



Заполнение с помощью генераторов случайных чисел: NumPy предоставляет функции для создания массивов со случайными значениями, такие как numpy.random.rand(), numpy.random.randint() и другие.

In [ ]:
import numpy as np

# Создание массива размером 2x3 со случайными значениями от 0 до 1
random_array = np.random.rand(3,3)

# Создание массива размером 2x3 со случайными целыми значениями от 0 до 9
random_int_array = np.random.randint(0, 10, (3, 3))

print(random_array,end = '\n\n')

print(random_int_array,end = '\n\n')


[[0.19728782 0.80441597 0.6857936 ]
 [0.50750282 0.75384703 0.36725912]
 [0.92638666 0.82229297 0.75181375]]

[[5 0 7]
 [0 5 6]
 [0 0 2]]



### Изменение размеров массива

Если что-то не устраивает, мы всегда можем видоизменить массив.

**reshape()** позволяет изменить форму (shape) массива без изменения его данных.
Новая форма должна содержать ту же общую длину (количество элементов) массива.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

reshaped_arr = np.reshape(arr, (3, 2))  # Изменяем форму на (3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = a.reshape(3,2)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


Метод **resize()** изменяет форму массива, добавляя или удаляя элементы при необходимости.

In [ ]:
arr = np.array([[1, 2],
                [3, 4]])

# Изменяем форму массива на (3, 3) с заполнением нулями
arr.resize((3, 3))
print(arr, end = '\n\n')

# Изменяем форму массива на (2, 2) с обрезкой
arr.resize((2, 2))
print(arr)

[[1 2 3]
 [4 0 0]
 [0 0 0]]

[[1 2]
 [3 4]]


In [ ]:
a = np.array([[1, 2],
                [3, 4]])
# с помощью этой команды можно вытянуть массив в одномерную "строку"
a.flatten()

array([1, 2, 3, 4])

###Срезы и индексация

Для одномерных массивов срезы и индексация работают также как и с list().

In [ ]:
a = np.array([1, 9, 3, 4, 5, 8, 90])

print(a[0])
print( a[3])
print( a[-1])
a[0] = '5'
print('new: ', a[0])

print(a[1:3])
print( a[3::2])
print( a[::-1])

1
4
90
new:  5
[9 3]
[4 8]
[90  8  5  4  3  9  5]


Многомерные немного отличаются от list()

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7 , 8, 9]]

a = np.array(lst, int)

print(lst[0][0], a[0,0], sep = ' : ', end = '\n\n')
print(lst[1][2], a[1,2], sep = ' : ', end = '\n\n')
print(lst[-1][-2], a[-1,-2], sep = ' : ', end = '\n\n')

1 : 1

6 : 6

8 : 8



In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7 , 8, 9]]

a = np.array(lst, int)
print(a,end = '\n\n')

print( a[ 1 , : ] ,end = '\n\n') # 4,5,6
print(a[ : , 2 ],end = '\n\n') # 3,6,9
print(a[-1 : , -2 : ],end = '\n\n') # 8,9

print(type(a))
print(type(a[-1 : , -2 : ]) )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[4 5 6]

[3 6 9]

[[8 9]]

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Срезы с шагом

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7 , 8, 9]]

a = np.array(lst, int)
print(a,end = '\n\n')
print(a[::2 , ::2 ])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 3]
 [7 9]]


Можно использовать не одиночные индексы, а списки индексов вдоль каждой оси:

In [ ]:
A = np.arange(5)
print(A)

index_list = [0, 1, -1]
A[index_list]


[0 1 2 3 4]


array([0, 1, 4])

В NumPy также реализована возможность доступа ко множеству элементов массива через булев индексный массив. Индексный массив должен совпадать по форме с индексируемым.



In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
I = np.array([[False, False, True], [ True, False, True]])
print(A[I])

[3 4 6]


###Характеристики массивов

In [ ]:

a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
print(a.shape) # Размерность массива
print(a.shape[0])

(2, 3)
2


In [ ]:
a.dtype # тип данных в массиве

dtype('float64')

In [ ]:
a.size # общее количество элементов

6

In [ ]:
a.ndim # размерность массива

2

###Математические операции над массивами

В NumPy мы можем произодить различные математические операции над массивами. Эти операции будут производиться поэлементно.

**Стандартные математические операции применимы только к массивам одинаковых размеров.**

In [ ]:
a = np.array([1, 2, 3], dtype=float)
b = np.array([5, 7, 8], dtype=float)
print('a: ', a)
print('b: ', b)

a:  [1. 2. 3.]
b:  [5. 7. 8.]


In [ ]:
b + 10

array([15., 17., 18.])

In [ ]:
b * 3

array([15., 21., 24.])

In [ ]:
a + b # Одинаковая размерность!

array([ 6.,  9., 11.])

In [ ]:
a - b

array([-4., -5., -5.])

In [ ]:
a * b

array([ 5., 14., 24.])

In [ ]:
a / b

array([0.2       , 0.28571429, 0.375     ])

In [ ]:
a % b

array([1., 2., 3.])

In [ ]:
b ** a

array([  5.,  49., 512.])

In [ ]:
a[1:] + b # Размерности не совпадают!

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

Также можем использовать различные унарные операции:

In [ ]:
import numpy as np

arr = np.array([[1, -2],
                [3, -4]])

print("Отрицание:")
print(-arr,end = '\n\n')

print("Абсолютное значение:")
print(np.abs(arr),end = '\n\n')

print("Возведение в степень:")
print(np.power(arr, 2),end = '\n\n')

print("Квадратный корень:")
print(np.sqrt(np.abs(arr)))


Отрицание:
[[-1  2]
 [-3  4]]

Абсолютное значение:
[[1 2]
 [3 4]]

Возведение в степень:
[[ 1  4]
 [ 9 16]]

Квадратный корень:
[[1.         1.41421356]
 [1.73205081 2.        ]]
Округление по правилам математики
[1. 2. 3.]



### Простые операции над массивами

Для любой размерности операции проводятся по всем элементам

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Сумма всех элементов:")
print(arr.sum())

print('Перемножение:')
print(arr.prod())

print("Среднее значение:")
print(arr.mean())

print("Минимальное значение:")
print(arr.min())

print("Максимальное значение:")
print(arr.max())


Сумма всех элементов:
21
Перемножение:
720
Среднее значение:
3.5
Минимальное значение:
1
Максимальное значение:
6
Максимальное значение:
[1 2 3 4 5 6]


Аналогично можно делать с одномерными массивами.

In [ ]:
a = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

print('массив уникальных значений ',np.unique(a)) # уникальные значчения. При воздействии на многомерный массив вернёт всё ещё одномерный.
print('Индекс минимального значения ',a.argmin()) #  Если массив имеет несколько измерений, метод вернет индекс минимального элемента в "сплющенном" (flatten) массиве
print('Индекс максимльного значения ',a.argmax())

массив уникальных значений  [1 2 3 4]
массив уникальных значений  0
массив уникальных значений  6


In [100]:
a = np.array([1,1, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements, counts = np.unique(a, return_counts=True)

print(counts) # количество повторений каждого элемента

[2 1 3 4]


А если мы хотим в многомерном массиве проводить операции построчно ( или по столбцам)???

In [ ]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print('Сумма элементов по столбцам (ось 0):',arr.sum(axis=0))

print('Сумма элементов по строкам (ось 1):',arr.sum(axis=1))


print('Минимальные значения по столбцам (ось 0):',arr.min(axis=0))

print('Максимальные значения по строкам (ось 1):',arr.max(axis=1))


Сумма элементов по столбцам (ось 0): [5 7 9]
Сумма элементов по строкам (ось 1): [ 6 15]
Минимальные значения по столбцам (ось 0): [1 2 3]
Максимальные значения по строкам (ось 1): [3 6]


Также мы можем производить различные округления

In [ ]:
a = np.array([1.1, 1.5, 1.9], float)

# округление вниз
print(np.floor(a))

# округление вврех
print(np.ceil(a))

# округление по правилам математики
print(np.rint(a))

[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]


###Логические операции над массивами

Мы можем поэлемантно выполнять:

Операции сравнения: Эти операции сравнивают каждый элемент массива с заданным значением ( или элементом другого массива) и возвращают массив булевых значений (True/False) в соответствии с выполнением условия.

Логические операции: Эти операции позволяют комбинировать результаты других логических операций для создания более сложных условий.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Операция сравнения: Возвращает массив булевых значений, указывающих,
# является ли каждый элемент массива arr больше 2
print(arr > 2)

# Использование результата операции сравнения для индексации массива:
# Выводит элементы массива, которые удовлетворяют условию arr > 2
print(arr[arr > 2])

[False False  True  True  True]
[3 4 5]


In [ ]:
a = np.array([1, 3, 0, 5])
b = np.array([0, 3, 2, 5])

print(a > b, type(a>b))

[ True False False False] <class 'numpy.ndarray'>


In [ ]:
c = a > b
c

array([ True, False, False, False])

In [ ]:
a[c] # a[a>b]

array([1])

In [ ]:
c = b > a
print(b[c]) # b[b>a]

[2]


In [ ]:
b[ b == a]

array([3, 5])

In [ ]:
c = b == a

print(c)
print(sum(c)) # сколько всего True
print(any(c)) # есть ли хоть один True
print(all(c)) # все ли True

[False  True False  True]
2
True
False


Если мы хотим поэлементно произвести операции ИЛИ / И / НЕ, то нам понадобятся специальные функции

In [ ]:
bool_arr1 = np.array([True, True, False, False])
bool_arr2 = np.array([True, False, True, False])

# Операция AND (логическое И): Возвращает массив, где элементы будут True
# только в случае, если оба соответствующих элемента в bool_arr1 и bool_arr2 являются True
print('И: ',np.logical_and(bool_arr1, bool_arr2))

# Операция OR (логическое ИЛИ): Возвращает массив, где элементы будут True
# если хотя бы один из соответствующих элементов в bool_arr1 или bool_arr2 является True
print('ИЛИ: ',np.logical_or(bool_arr1, bool_arr2))

print('НЕ: ',np.logical_not(bool_arr1))

И:  [ True False False False]
ИЛИ:  [ True  True  True False]
НЕ:  [False False  True  True]


In [ ]:
bool_arr1 = np.array([True, True, False, False])
bool_arr2 = np.array([True, False, True, False])

print(bool_arr1 and bool_arr2) # не получится

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Мы можем использовать */+  вместо np.logical_and() / np.logical_or(), но это будет плохо читаемо.

In [ ]:
bool_arr1 = np.array([True, True, False, False])
bool_arr2 = np.array([True, False, True, False])

# Использование оператора * для выполнения элементарного умножения (логического И)
print(bool_arr1 * bool_arr2)



[ True False False False]


Можно проверять элементы массива на наличие NaN и бесконечностей.

In [ ]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [ ]:
np.isnan(a) # Является ли элемент массива nan

array([False,  True, False])

In [ ]:
np.isfinite(a) # является ли элемент массива конечным числом

array([ True, False, False])

## Задания на пройденный материал

###№1 Создание 1
Создайте массив arr, который содержит числа от 1 до 23 включительно с шагом 2 и преобразуйте его в двумерный массив размером 4x2.

###Пример решения

In [ ]:
import numpy as np

arr = np.arange(1, 24, 2)

arr = arr.reshape(4, 3)
print(arr)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


###№2 Создание 2
Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```
Не следует явно прописывать данную матрицу.

###Пример решения

In [ ]:
matrix = np.zeros((10, 10))

matrix[[0, -1], :] = 1
matrix[:, [0, -1]] = 1

print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###№3 Создание 3
Создайте матрицу ```7x7``` с числами 11..17 на главной диагонали и с 0 в других местах. Выведите её.

###Пример решения

In [ ]:
a = np.eye(7)
a[a == 1] = np.arange(11,18)
print(a)

[[11.  0.  0.  0.  0.  0.  0.]
 [ 0. 12.  0.  0.  0.  0.  0.]
 [ 0.  0. 13.  0.  0.  0.  0.]
 [ 0.  0.  0. 14.  0.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0.  0. 16.  0.]
 [ 0.  0.  0.  0.  0.  0. 17.]]


###№4 Создание 4
У матрицы из предыдущего задания замените нули выше и ниже диагонали на числа -1 .. -6.

###Пример решения

In [ ]:
a = np.eye(7)
a[a == 1] = np.arange(11,18)
a += np.eye(7,k = 1)
a[ a == 1] = np.arange(-6,0)
a += np.eye(7,k = -1)
a[ a == 1] = np.arange(-6,0)
print(a)

[[11. -6.  0.  0.  0.  0.  0.]
 [-6. 12. -5.  0.  0.  0.  0.]
 [ 0. -5. 13. -4.  0.  0.  0.]
 [ 0.  0. -4. 14. -3.  0.  0.]
 [ 0.  0.  0. -3. 15. -2.  0.]
 [ 0.  0.  0.  0. -2. 16. -1.]
 [ 0.  0.  0.  0.  0. -1. 17.]]


###№5 Замена
Дана матрица ```10x10```

```
arr = np.array([[34, 10, 27, 32, 38, 21, 46, 17, 29, 48],
                   [41, 35, 28, 12, 37, 46, 26, 20, 39,  5],
                   [49, 50, 18, 20, 20,  9, 33, 47, 12, 50],
                   [19, 50, 37, 27, 10, 15, 39, 27,  6, 33],
                   [13, 31, 32, 27, 16,  1, 34, 13, 20, 22],
                   [14, 15, 42,  7, 38,  5, 27, 50, 14, 20],
                   [42,  8, 21, 48, 26, 28, 16, 22, 11, 28],
                   [14, 30, 40, 38, 40, 33, 26, 19, 49, 48],
                   [ 7, 36, 47, 36, 50, 11, 13, 28, 48, 47],
                   [25, 48, 41,  1, 40, 34, 44, 50, 29, 28]],float)
```
Замените во всех чётных строках (0,2,4,6,8) числа, которые больше 7 и нацело деляться на 5 на нули.

###Пример решения

In [98]:
arr = np.array([[34, 10, 27, 32, 38, 21, 46, 17, 29, 48],
                   [41, 35, 28, 12, 37, 46, 26, 20, 39,  5],
                   [49, 50, 18, 20, 20,  9, 33, 47, 12, 50],
                   [19, 50, 37, 27, 10, 15, 39, 27,  6, 33],
                   [13, 31, 32, 27, 16,  1, 34, 13, 20, 22],
                   [14, 15, 42,  7, 38,  5, 27, 50, 14, 20],
                   [42,  8, 21, 48, 26, 28, 16, 22, 11, 28],
                   [14, 30, 40, 38, 40, 33, 26, 19, 49, 48],
                   [ 7, 36, 47, 36, 50, 11, 13, 28, 48, 47],
                   [25, 48, 41,  1, 40, 34, 44, 50, 29, 28]],float)

bool_matrix = np.logical_and(arr[::2,:] > 7, arr[::2,:] % 5 == 0 )

arr[::2,:][bool_matrix] = 0
print(arr)

[[34.  0. 27. 32. 38. 21. 46. 17. 29. 48.]
 [41. 35. 28. 12. 37. 46. 26. 20. 39.  5.]
 [49.  0. 18.  0.  0.  9. 33. 47. 12.  0.]
 [19. 50. 37. 27. 10. 15. 39. 27.  6. 33.]
 [13. 31. 32. 27. 16.  1. 34. 13.  0. 22.]
 [14. 15. 42.  7. 38.  5. 27. 50. 14. 20.]
 [42.  8. 21. 48. 26. 28. 16. 22. 11. 28.]
 [14. 30. 40. 38. 40. 33. 26. 19. 49. 48.]
 [ 7. 36. 47. 36.  0. 11. 13. 28. 48. 47.]
 [25. 48. 41.  1. 40. 34. 44. 50. 29. 28.]]


###№6 Частота
Дан одномерный массив.
  ```
  arr = np.array([ 9,  2,  8,  4,  6,  9,  1,  1,  3,  7, 10,  3,  7,  8,  4,  6,  7,  5, 10,  5,  2,  8, 10])
  ```
   Найти наиболее частое значение в массиве.

###Пример решения

In [106]:
arr = np.array([ 9,  2,  8,  4,  6,  9,  1,  1,  3,  7, 10,  3,  7,  8,  4,  6,  7,  5, 10,  5,  2,  8, 10])

unique_elements, counts = np.unique(arr, return_counts=True)

# Находим индекс элемента с наибольшим количеством повторений
most_common_index = np.argmax(counts)

# Наиболее частое значение
most_common_value = unique_elements[most_common_index]

print(most_common_value)

7


###№7 Средний рост учеников
В классе учатся 20 учеников. Мы имеемм данные о росте каждого из них.
```
st_len = np.array([152, 156, 160, 162, 165, 168, 170, 181, 180, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196])


```
 Необходимо вычислить средний рост в классе, а также определить, сколько учеников выше среднего роста, а сколько ниже.

###Пример решения

In [109]:
st_len = np.array([152, 156, 160, 162, 165, 168, 170, 181, 180, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196])

average_height = np.mean(st_len)

above_average = np.sum(st_len > average_height)
below_average = np.sum(st_len < average_height)

print(average_height)
print(above_average)
print(below_average)


177.0
12
8


###№8 Минимальный среди максимальных
Дан массив ```10x10 ```

```
matrix = np.array([
    [ 65,  53,  89,  58,  93,  94,  63,  64,  41,  43],
    [ 39,  68,  97,  89,  91,  82,  90,  27,  97,  34],
    [ 97,  94,  50,  78,  58,  26,  15,  36,  20,  38],
    [ 95,  76,  35,  66,  77,  64,  68,  47,  74,  40],
    [ 89,  63,  92,  21,  89,  88,  89,  63,  18,  13],
    [  4,  46,  94,  17,  81,  75,  22,  71,  63,  29],
    [ 90,  48,  19,  47,  26,  41,  68,  53,  34,  69],
    [ 25,  50,  49,  25,  59,  77,  48,  19,  24,  17],
    [ 47,  73,  90,  11,  52,  67,  36,  99,  21,  29],
    [ 58,  34,  93,  89,  63,  79,  40,  94,  42,  55]
])
```
Найдите минимальное значение максимальных значений столбцов, а также среднее значение минимальных значений строк.

###Пример решения

In [112]:
import numpy as np

matrix = np.array([
    [ 65,  53,  89,  58,  93,  94,  63,  64,  41,  43],
    [ 39,  68,  97,  89,  91,  82,  90,  27,  97,  34],
    [ 97,  94,  50,  78,  58,  26,  15,  36,  20,  38],
    [ 95,  76,  35,  66,  77,  64,  68,  47,  74,  40],
    [ 89,  63,  92,  21,  89,  88,  89,  63,  18,  13],
    [  4,  46,  94,  17,  81,  75,  22,  71,  63,  29],
    [ 90,  48,  19,  47,  26,  41,  68,  53,  34,  69],
    [ 25,  50,  49,  25,  59,  77,  48,  19,  24,  17],
    [ 47,  73,  90,  11,  52,  67,  36,  99,  21,  29],
    [ 58,  34,  93,  89,  63,  79,  40,  94,  42,  55]
])

# Найдем максимальные значения для каждого столбца и затем найдем минимальное из них
max_values = matrix.max(axis=0)
min_of_max = max_values.min()

# Найдем минимальные значения для каждой строки и затем найдем среднее из них
min_values = matrix.min(axis=1)
average_of_min = min_values.mean()

print(min_of_max)
print(average_of_min)


69
21.6


###№9 N первых
Дана матрица.
```
matrix = np.array([
    [ 65,  53,  89,  58,  93,  94,  63,  64,  41,  43],
    [ 39,  68,  97,  89,  91,  82,  90,  27,  97,  34],
    [ 97,  94,  50,  78,  58,  26,  15,  36,  20,  38],
    [ 95,  76,  35,  66,  77,  64,  68,  47,  74,  40],
    [ 89,  63,  92,  21,  89,  88,  89,  63,  18,  13],
    [  4,  46,  94,  17,  81,  75,  22,  71,  63,  29],
    [ 90,  48,  19,  47,  26,  41,  68,  53,  34,  69],
    [ 25,  50,  49,  25,  59,  77,  48,  19,  24,  17],
    [ 47,  73,  90,  11,  52,  67,  36,  99,  21,  29],
    [ 58,  34,  93,  89,  63,  79,  40,  94,  42,  55]
])
```
Найти n наибольших значений в массиве. n вводится с клавиатуры.
Выведите значения в порядке возрастания.

###Пример решения

In [119]:
n = int(input())

matrix = np.array([
    [ 65,  53,  89,  58,  93,  94,  63,  64,  41,  43],
    [ 39,  68,  97,  89,  91,  82,  90,  27,  97,  34],
    [ 97,  94,  50,  78,  58,  26,  15,  36,  20,  38],
    [ 95,  76,  35,  66,  77,  64,  68,  47,  74,  40],
    [ 89,  63,  92,  21,  89,  88,  89,  63,  18,  13],
    [  4,  46,  94,  17,  81,  75,  22,  71,  63,  29],
    [ 90,  48,  19,  47,  26,  41,  68,  53,  34,  69],
    [ 25,  50,  49,  25,  59,  77,  48,  19,  24,  17],
    [ 47,  73,  90,  11,  52,  67,  36,  99,  21,  29],
    [ 58,  34,  93,  89,  63,  79,  40,  94,  42,  55]
])

flat_matrix = matrix.flatten()

# Сортируем плоский массив в порядке возрастания
sorted_flat = np.sort(flat_matrix)

# Получаем n наибольших значений
top_n = sorted_flat[-n:]
print(top_n)

5
[95 97 97 97 99]
